## workflow build config

# id and name for the workflow (bundle id = domain.id)
id: alfred-kibela-workflow

# base domain
domain: com.kakunpc

name: kibela
description: Alfredでkibelaを検索できます
created_by: kakunpc
website: https://github.com/kakunpc
readme: kibela setup で設定が必要です。

## development config

# path is the relative path to the workflow in the project root
path: workflow

# If you are using Alfred's advanced Dropbox sync, indicate the path shown in
# Alfred Preferences > Advanced > Syncing:
dropbox: ~/Dropbox